#pragma once
#include "NativeGameplayTags.h"

namespace InteractionGameplayTags
{
	SURVIVALGAMEINTERACTIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Primary)
	SURVIVALGAMEINTERACTIONRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Secondary)
	
}
